### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by XXXSadWolfXXX** [designer1337/aristois-legit#1]
Hi i have some problems
After turn on Weapon ESP game crashing, and when i turn on backtrack i hear "stranger things" and Knifechanger not working. You know how to fix it? or you can fix it?

**Comment by designer1337** [comment]
There was csgo update last night, cheat needs updated class Id

I can't fix this cuz im not in home right now

**Comment by XXXSadWolfXXX** [comment]
ok, but if you back to home please fix. I love this cheat :)

**Comment by designer1337** [comment]
Of course I will
