### ISSUE TITLE
Shooting in menu

### ISSUE THREAD

**Issue by MrClue** [designer1337/aristois-legit#10]
If you open the menu and click two times in a row, you will start to shoot your gun even though menu is open.

Maybe we should check if menu is open, and if it is open, then disable fire key or something?
Idk where that code was located in the source :p

**Comment by rafalohaki** [comment]
+

**Comment by w3x13** [comment]
there was a cvar for disabling mouse, but idk if its on the modern source

**Comment by brunph** [comment]
Repository owner has to add the input_system interface and use the enable_input function to make sure that no input gets out when the menu is open.

**Comment by w3x13** [comment]
if (c_menu::get().opened)
	{
		interfaces::inputsystem->enable_input(false);

	}
	else if (!c_menu::get().opened)
	{
		interfaces::inputsystem->enable_input(true);

	}


add this in hooks.cpp
