### ISSUE TITLE
Cursor dissapearing when closing menu.

### ISSUE THREAD

**Issue by w3x13** [designer1337/aristois-legit#11]
When i open the menu it pushes a custom cursor, but after closing it doesnt reload csgos one.

**Comment by designer1337** [comment]
open console (press ~ on your keyboard) as a temp fix

**Comment by w3x13** [comment]
or just tab out and back in.

**Comment by atheleon** [comment]
https://i.imgur.com/em9HTSd.png

**Comment by designer1337** [comment]
fixed, thanks.
