### ISSUE TITLE
We need to optimize chams drawing

### ISSUE THREAD

**Issue by MrClue** [designer1337/aristois-legit#12]
I am trying to figure out a way so that if we draw chams through walls, it shouldnt apply chams if enemy is not behind a wall. If anyone can help with this, it would be really nice!

Right now it is applying the chams to all models, even if they are visible. If you only enable the invisible chams option, it still draws on players that are visible and avoiding this will save some FPS and will make it possible to do other cool stuff to invisible models only =)

**Comment by designer1337** [comment]
just add check for visible chams

```
if !can_see_player_pos()
           return;
```

**Comment by MrClue** [comment]
Like this glitches the chams
`if (!local_player->can_see_player_pos(entity, entity->get_eye_pos()))
			return;

		if (c_config::get().vis_chams_vis) {
			interfaces::render_view->modulate_color(c_config::get().clr_chams_vis);
			interfaces::render_view->set_blend(c_config::get().clr_chams_vis[3]);
			mat->set_material_var_flag(MATERIAL_VAR_IGNOREZ, false);

			interfaces::model_render->override_material(mat);
			entity->draw_model(1, 255);
		}

		if (c_config::get().vis_chams_invis) {
			interfaces::render_view->modulate_color(c_config::get().clr_chams_invis);
			interfaces::render_view->set_blend(c_config::get().clr_chams_invis[3]);
			mat->set_material_var_flag(MATERIAL_VAR_IGNOREZ, true); //crash without increment_reference_count - designer

			interfaces::model_render->override_material(mat);
			entity->draw_model(1, 255);
		}

		interfaces::model_render->override_material(nullptr);
	}`
