### ISSUE TITLE
'aim on records' is really bad

### ISSUE THREAD

**Issue by ultramemer** [designer1337/aristois-legit#13]
![btissue](https://user-images.githubusercontent.com/31269663/57575410-54c75280-7452-11e9-9c12-507cbbce7daa.gif)
worst gif ever on planet earth
but you get what i mean

also fix this
https://github.com/designer1337/aristois-legit/blob/master/core/features/backtrack/backtrack.cpp#L129
you already check for IN_ATTACK at the beginning

**Comment by designer1337** [comment]
I guess it's engine prediction issue, I'll take a look  tomorrow

**Comment by MrClue** [comment]
If you try to shoot on the latest tick-cham, your backtrack doesn't even go that far.
I think there is something wrong with the latest tick or the chams are drawn after that last tick or something.

**Comment by ultramemer** [comment]
i made a function that loops through all available entity records and returns the last valid one
did some tests and found out that the last valid record is always 3 records behind the last available one
tried to remove calls to engine prediction in createmove and it didnt change anything
dont know what is wrong, i dont have that problem in osiris
