### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by zerojoshua** [designer1337/aristois-legit#14]
Always crashes whenever I change skin (I know its a WIP), Also crashes whenever I die or a aimlock onto someone then shoot (Skins also go black sometimes), Ty :) (Oh and if you could, Do you think you could add a custom model changer? Would be sick.

Oh and if you have a discord I could suggest some stuff to you and maybe help you with this? XD ty again for working on this for everyone to play with :) 👍

**Comment by whyyy666** [comment]
yeah same, crashes all the time sometimes while killing someone with headshot or i get killed or after enabling some features like chams i hope he can fix this asap cause this cheat is just awesome, keep up the good work @designer1337

**Comment by bximing** [comment]
Yeah I keep crashing when I load into an arms race match. Good cheat besides that tho

**Comment by designer1337** [comment]
designer#1824
