### ISSUE TITLE
esp stays on screen

### ISSUE THREAD

**Issue by tonti666** [designer1337/aristois-legit#26]
https://i.imgur.com/5OHykmv.jpg

**Comment by w3x13** [comment]
Is this after unload or after killing the enemy? 

never happend to me either way /shrug

**Comment by tonti666** [comment]
neither, if the enemy was there sometimes it's esp stays there

**Comment by designer1337** [comment]
dormat check bug

**Comment by w3x13** [comment]
yeah ehm, never happened to me, idk if ur dormant is fucked or what
