### ISSUE TITLE
Visualize backtrack issues

### ISSUE THREAD

**Issue by w3x13** [designer1337/aristois-legit#29]
if (entity && !entity->dormant()) {
				if (local_player && entity->team() != local_player->team()) {
					for (int t = 1; t < 12; ++t) {
						if (entity_data[i][t].simtime && entity_data[i][t].simtime + 1 > local_player->simulation_time())
							original_fn(interfaces::model_render, ctx, state, info, bone_data[i][t].bone_matrix);
					}
				}
			}

Exception thrown at 0x50D1F20F (cheat.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x51A0282C.

**Comment by designer1337** [comment]
It's old and not even used anymore
