### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by CroutonSilent** [designer1337/aristois-legit#39]
I saw u closed my case about this issue but even after the new update it still crashes
The cfg issue is still crashing me
"When I make a new config and save it
When i try to load it it crashes
When it doesnt crash everything is disabled
Im using the latest version"

**Comment by forntorn** [comment]
dude make a new config. every update the old configs break.

**Comment by CroutonSilent** [comment]
> dude make a new config. every update the old configs break.

ya see heres the thing. 
My old cfgs work fine
When i make new one and load them they break
