### ISSUE TITLE
Excuse me,I have a little problem. It's not important. 

### ISSUE THREAD

**Issue by HeiDaShuai666** [designer1337/aristois-legit#44]
Excuse me,I have a little problem. It's not important. 
When the enemy's name is in Chinese, display Random code on their heads.
Similarly, when the name of the spectators is Chinese, it also shows random code.
![The blue Chinese name on the top is his correct name, and the Random code name on the bottom](https://user-images.githubusercontent.com/42376695/58222189-c7380c80-7d47-11e9-8837-eae49643d226.png)

Sometimes "got v" appears under spectators on the right side of the screen, but there is no such person in the team and enemy team.What is it?
![There is no got V on the left, and spectators on the right sometimes appear below](https://user-images.githubusercontent.com/42376695/58222201-cd2ded80-7d47-11e9-95ee-bc97ca3f83fe.png)

**Comment by designer1337** [comment]
Change cheat font to one that supports Chinese language
