### ISSUE TITLE
When the name at the top of the Enemy is Chinese, it will appear garbled.

### ISSUE THREAD

**Issue by HeiDaShuai666** [designer1337/aristois-legit#45]
When the name at the top of the character is Chinese, it will appear garbled.
for example，枪王，超神。

**Comment by forntorn** [comment]
Change cheat font to one that supports Chinese language

**Comment by designer1337** [comment]
As above

**Comment by HeiDaShuai666** [comment]
I tried to change the fonts of watermark_font and name_font, but still appear garbled.

misc.cpp
ss << "中文" << " | fps: "  << fps << " | incoming: " << incoming.c_str() << "ms" << " | outgoing: " << outgoing.c_str() << "ms";
![TIM截图20190523170700](https://user-images.githubusercontent.com/42376695/58240272-409e2200-7d7d-11e9-8d05-e03b163c68b6.png)

render.hpp
void setup_fonts() {

		watermark_font = interfaces::surface->font_create();
		name_font = interfaces::surface->font_create();
		interfaces::surface->set_font_glyph(watermark_font,  "msyh", 12, 500, 0, 0, font_flags::fontflag_dropshadow);//msyh.ttf
		interfaces::surface->set_font_glyph(name_font, "simhei", 12, 500, 0, 0, font_flags::fontflag_antialias | font_flags::fontflag_dropshadow);//simhei.ttf
		printf("Render initialized!\n");
	}

**Comment by forntorn** [comment]
try msyh.ttf
simhei.ttf
