### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by Th3yS33M3** [designer1337/aristois-legit#46]
Any ideas?

> 1>------ Build started: Project: aristois beta, Configuration: Release Win32 ------
1>aimbot.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>backtrack.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>logs.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>events.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>hitmarker.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>misc.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>prediction.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>movement.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>parser.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>skinchanger.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>nightmode.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>sound.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>visuals.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>hooks.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>config.cpp
1>menu.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>interfaces.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>math.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>utilities.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>hook.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>Compiling...
1>main.cpp
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(388): error C3861: 'get': identifier not found
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C2039: 'get': is not a member of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\dependencies\math\math.hpp(7): note: see declaration of 'c_math'
1>B:\Stuff\Sources\CSGO Legit sources\aristois-legit-master_bak\source-sdk\classes\entities.hpp(389): error C3861: 'get': identifier not found
1>Done building project "csgo-cheat.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by MrClue** [comment]
probably fucked up on `{
}`
Somewhere in the code.

**Comment by Th3yS33M3** [comment]
I made zero changes to this version (most recent) had no issues before this, also all project settings seem to be original :o

**Comment by Archie2525** [comment]
in entities.hpp change any
`c_math::get().`
to
`math.`

**Comment by designer1337** [comment]
As above, update new source it should be fine

**Comment by designer1337** [comment]
Fixed.

**Comment by Th3yS33M3** [comment]
Thank you guys :) Has been a great source to have fun with :p
