### ISSUE TITLE
Need help with menu

### ISSUE THREAD

**Issue by MrClue** [designer1337/aristois-legit#47]
How do i center the font (marked with green).
And how do i make this part bigger (marked with red).

![jajajaja](https://user-images.githubusercontent.com/27066853/58297181-1f6a1f80-7dd7-11e9-9177-18b2cac2f161.PNG)

Thanks :)

**Comment by designer1337** [comment]
https://github.com/designer1337/aristois-legit/blob/cf17d3a0c415926a904b1fe9255bffa18b5e6e04/core/menu/menu.cpp#L102

https://github.com/designer1337/aristois-legit/blob/cf17d3a0c415926a904b1fe9255bffa18b5e6e04/core/menu/menu.cpp#L97

https://github.com/designer1337/aristois-legit/blob/cf17d3a0c415926a904b1fe9255bffa18b5e6e04/core/menu/menu.cpp#L98
