### ISSUE TITLE
Bhop min hop issue

### ISSUE THREAD

**Issue by MrClue** [designer1337/aristois-legit#50]
It seems if you have a bhop hit chance of lower than 100 then there is a chance of it missing the min hop.

Wouldnt it be better to ignore the hit chance for the first min_hops?
Example: min hop = 1, so the hit chance for a bhop should always be 100% during the first bhop, then afterwards it should apply the hit chance?

**Comment by forntorn** [comment]
thats literally the whole point of a "legit bhop" dude. if you dont want to miss hops put at 100%

**Comment by forntorn** [comment]
or dont even turn on hitchance

**Comment by designer1337** [comment]
thats the point of a legit bhop as mentioned above
