### ISSUE TITLE
Help with source

### ISSUE THREAD

**Issue by MrClue** [designer1337/aristois-legit#54]
what is this called `g_vHitPosition = pTrace.m_vEndPosition;`
In this source?

**Comment by MrClue** [comment]
Making a different recoil crosshair

**Comment by MrClue** [comment]
`trace_t pTrace;`

**Comment by designer1337** [comment]
https://github.com/designer1337/aristois-legit/blob/7e90867e64e68d628d72a29655a27dad190fb6db/dependencies/interfaces/i_trace.hpp
