### ISSUE TITLE
[Contribution] Nearest hitbox and hitbox per weapon group

### ISSUE THREAD

**Issue by megapaster** [designer1337/aristois-legit#61]
code: https://pastebin.com/r5ErZTxL
ss: https://cdn.discordapp.com/attachments/411702001437769729/587099933908271110/unknown.png

**Comment by MrClue** [comment]
Thanks a lot my friend, didnt realise how easy it was to do this

**Comment by megapaster** [comment]
> Thanks a lot my friend, didnt realise how easy it was to do this

np bro. If you want to add silent aim per groups its literally the same.

			if (!config_system.item.pistol_silent && is_pistol(weapon)) {
				interfaces::engine->set_view_angles(user_cmd->viewangles);
			}

**Comment by designer1337** [comment]
Thanks for sharing :)

**Comment by nertigel** [comment]
too much code.
c_aimbot::weapon_settings, bool nearestHitbox; add a check in every weapon group: if (is_pistol(weapon)), nearestHitbox = config_system.item.legitbot.pistol_nearesthitbox.
