### ISSUE TITLE
Question about menu

### ISSUE THREAD

**Issue by MrClue** [designer1337/aristois-legit#62]
Why do we define the colors of imgui inside menu.hpp if they get redefined in menu.cpp every time we use the PushStyleColor function?

example in menu.hpp we say: 
`		colors[ImGuiCol_ChildWindowBg] = ImVec4(33 / 255.f, 35 / 255.f, 47 / 255.f, 1.0f);
`
and then in menu.cpp we say:
`				ImGui::PushStyleColor(ImGuiCol_ChildWindowBg, ImVec4(30 / 255.f, 30 / 255.f, 39 / 255.f, 1.0f));
`
is there a smarter way to do this in menu.cpp now that we already stated it in menu.hpp?

**Comment by designer1337** [comment]
PushStyleColor is used to change color of various elements, for example u can change one groupbox outline to red and other to green

**Comment by MrClue** [comment]
> PushStyleColor is used to change color of various elements, for example u can change one groupbox outline to red and other to green

I know, but what is the point of having anything related to colors inside menu.hpp?

**Comment by designer1337** [comment]
> > PushStyleColor is used to change color of various elements, for example u can change one groupbox outline to red and other to green
> 
> I know, but what is the point of having anything related to colors inside menu.hpp?

it defines default color for all items that use ImGuiCol_ChildWindowBg
