### ISSUE TITLE
[Contribution] Jump check and better weapon check

### ISSUE THREAD

**Issue by MrClue** [designer1337/aristois-legit#63]
Felt like I should contribute a little, instead of only leeching haha, so here we go:

**Jump check:**
In Aimbot.cpp under `void c_aimbot::run(c_usercmd* user_cmd) noexcept {`
paste this in with the rest of the checks:

````
//jump check (both local player and the entity) #MrClue
			if (!(local_player->flags() & fl_onground) || (!(entity->flags() & fl_onground)) && config_system.item.aim_jump_check)
				return;
````

And in config.hpp just add `bool aim_jump_check{ false };`
and then make a checkbox for this setting in the menu, should be easy >_>

**Better weapon check:**
search and find `bool is_grenade(void* weapon) {` 
yours will probably be inside aimbot.hpp

Now replace yours with this:
````
bool is_grenade(void* weapon) {
		if (!weapon)
			return false;

		auto current_weapon = reinterpret_cast<weapon_t*>(weapon);
		int id = current_weapon->item_definition_index();
		static const std::vector<int> v = { WEAPON_FRAG_GRENADE, WEAPON_HEGRENADE, WEAPON_INCGRENADE, WEAPON_SMOKEGRENADE, WEAPON_TAGRENADE, WEAPON_MOLOTOV, WEAPON_FLASHBANG };
		return (std::find(v.begin(), v.end(), id) != v.end());
	}
````
This should fix the random aimbotting with flashbangs for your weapon check.

**Comment by xbread** [comment]
make a pull request?
