### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Appbuilder11** [designer1337/aristois-legit#7]
Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory	aristois beta	D:\aristois-legit-master\dependencies	D:\aristois-legit-master\dependencies\common_includes.hpp	17	

I get like 22 of these tried everything cant get rid of it

**Comment by designer1337** [comment]
U need DirectX SDK.

**Comment by Appbuilder11** [comment]
I have it
