### ISSUE TITLE
New p2c name Pantsuware

### ISSUE THREAD

**Issue by fsnaix** [designer1337/aristois-legit#78]
https://www.facebook.com/pantsuware/?ref=br_rs
They are claiming this for themselves and selling it for 10.75$
![Untitled](https://user-images.githubusercontent.com/51787675/63182599-27a3c500-c07d-11e9-9daa-3ba10bc35902.png)
They can't even change the cfg folder

**Comment by designer1337** [comment]
lmaoooo

**Comment by fsnaix** [comment]
more evidence about panstu
[image: image.png]

Vào Th 7, 17 thg 8, 2019 vào lúc 15:21 designer1337 <
notifications@github.com> đã viết:
