### ISSUE TITLE
Grab Local player name

### ISSUE THREAD

**Issue by LuanGraa** [designer1337/aristois-legit#85]
Hello i added some features to this source related to name changing(fake VAC ban, fake vote, fake unbox) and until now i have "hardcoded" the names of the players in the messages because i can't seem to get the local player name it just returns a bunch of random chars.

`const char* utilities::get_local_player_name() {
	for (int i = 0; i < interfaces::entity_list->get_highest_index(); i++) {
		auto local_player = reinterpret_cast<player_t*> 
                (interfaces::entity_list>get_client_entity(interfaces::engine->get_local_player()));

		if (!local_player)
			return "nothing";

		auto entity = reinterpret_cast<player_t*>(interfaces::entity_list->get_client_entity(i));

		if (!entity)
			return "nothing";

		player_info_t info;

		if (entity && entity == local_player) {
			interfaces::engine->get_player_info(i, &info);
			std::string name = info.name;
			std::transform(name.begin(), name.end(), name.begin(), ::tolower);
			return name.c_str();
			break;
		}
	}
}`

**Comment by designer1337** [comment]
Why would u use break; here?

It's not a switch statement

**Comment by LuanGraa** [comment]
because i needed it to stop after it found the first player_name which normally is the local player name

**Comment by iBambooFox** [comment]
You clearly don't know what you're doing. I think this is stupid, but if you really need something that does the job, try this. You should be careful, the name in player info is not a string, but a char array.

```
void get_player_name(player_t* entity, std::string &entity_name) {
	if (!entity or !interfaces::engine->is_in_game())
		return;

	player_info_t player_info;
	interfaces::engine->get_player_info(entity, &player_info);
	
	entity_name += player_info.name;
}
```
also check your formatting
besides, you need not open an issue for this
