### ISSUE TITLE
Mistake in code

### ISSUE THREAD

**Issue by feliksz** [designer1337/aristois-legit#93]
https://github.com/designer1337/aristois-legit/blob/ed3c98988c5e5fa3a75a3f9b1297646e42c170bb/core/hooks/hooks.cpp#L275

Lmao, this was defined a line above???

https://github.com/designer1337/aristois-legit/blob/ed3c98988c5e5fa3a75a3f9b1297646e42c170bb/core/hooks/hooks.cpp#L1

This will throw an error.

**Comment by designer1337** [comment]
fixed
