### ISSUE TITLE
New P2C scam

### ISSUE THREAD

**Issue by jon4dev** [designer1337/aristois-legit#94]
Hi, i found new p2c who sell renamed aristois-legit

evidence:
discord message:
![1](https://user-images.githubusercontent.com/47613181/80124331-a7285300-857f-11ea-80fa-847a1177546a.png)

![unknown](https://user-images.githubusercontent.com/47613181/80124477-d8a11e80-857f-11ea-8503-4c9de9158403.png)

video "BIG PRIVATE H4CK"
https://www.youtube.com/watch?v=RbthOjLY6qk

**Comment by plisskien** [comment]
So sad...
